-- Anonymous recovery, clarification replies, content reporting, and HR thought moderation.

alter table private.question_threads
  add column if not exists employee_reply text,
  add column if not exists employee_reply_at timestamptz;

create table if not exists private.recovery_vaults (
  vault_hash text primary key check (vault_hash ~ '^[0-9a-f]{64}$'),
  ciphertext text not null check (char_length(ciphertext) between 1 and 200000),
  salt text not null check (char_length(salt) between 16 and 128),
  iv text not null check (char_length(iv) between 12 and 128),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists private.content_reports (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('question', 'thought')),
  target_id bigint not null,
  question_id bigint not null references public.questions(id) on delete cascade,
  reporter_hash text not null check (reporter_hash ~ '^[0-9a-f]{64}$'),
  reason text not null check (char_length(reason) between 3 and 1000),
  status text not null default 'open' check (status in ('open', 'reviewed', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (target_type, target_id, reporter_hash)
);

create index if not exists content_reports_open_question_idx
  on private.content_reports (question_id, created_at desc)
  where status = 'open';

alter table private.recovery_vaults enable row level security;
alter table private.content_reports enable row level security;

revoke all on private.recovery_vaults from public, anon, authenticated;
revoke all on private.content_reports from public, anon, authenticated;
grant all on private.recovery_vaults to service_role;
grant all on private.content_reports to service_role;

create or replace function public.get_unask_recovery_vault(p_vault_hash text)
returns table (ciphertext text, salt text, iv text, vault_version integer)
language sql
stable
security definer
set search_path = pg_catalog, private, public
as $$
  select rv.ciphertext, rv.salt, rv.iv, rv.version
  from private.recovery_vaults rv
  where public.is_everstage_user()
    and (select auth.uid()) is not null
    and p_vault_hash ~ '^[0-9a-f]{64}$'
    and rv.vault_hash = p_vault_hash;
$$;

create or replace function public.save_unask_recovery_vault(
  p_vault_hash text,
  p_ciphertext text,
  p_salt text,
  p_iv text,
  p_expected_version integer default 0
)
returns table (vault_version integer)
language plpgsql
security definer
set search_path = pg_catalog, private, public
as $$
declare
  v_current integer;
begin
  if not public.is_everstage_user() or (select auth.uid()) is null then
    raise exception 'Verified Everstage access is required';
  end if;
  if p_vault_hash is null or p_vault_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid recovery vault';
  end if;
  if char_length(coalesce(p_ciphertext, '')) not between 1 and 200000
    or char_length(coalesce(p_salt, '')) not between 16 and 128
    or char_length(coalesce(p_iv, '')) not between 12 and 128 then
    raise exception 'Invalid encrypted recovery payload';
  end if;

  select rv.version into v_current
  from private.recovery_vaults rv
  where rv.vault_hash = p_vault_hash
  for update;

  if not found then
    if coalesce(p_expected_version, 0) <> 0 then
      raise exception 'Recovery vault changed; restore it before saving again';
    end if;
    insert into private.recovery_vaults (vault_hash, ciphertext, salt, iv)
    values (p_vault_hash, p_ciphertext, p_salt, p_iv);
    return query select 1;
    return;
  end if;

  if coalesce(p_expected_version, 0) <> v_current then
    raise exception 'Recovery vault changed; restore it before saving again';
  end if;

  update private.recovery_vaults
  set ciphertext = p_ciphertext,
      salt = p_salt,
      iv = p_iv,
      version = version + 1,
      updated_at = now()
  where vault_hash = p_vault_hash
  returning version into v_current;

  return query select v_current;
end;
$$;

drop function if exists public.get_unask_question_thread(bigint, text);
create function public.get_unask_question_thread(
  p_question_id bigint,
  p_thread_hash text
)
returns table (
  id bigint,
  question text,
  detail text,
  status public.question_status,
  visibility public.question_visibility,
  display_name text,
  upvotes integer,
  dislikes integer,
  comments_count integer,
  responder_label text,
  answer text,
  private_reply text,
  employee_reply text,
  employee_reply_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = pg_catalog, private, public
as $$
  select q.id, q.question, q.detail, q.status, q.visibility, q.display_name,
    q.upvotes, q.dislikes, q.comments_count, q.responder_label, q.answer,
    t.private_reply, t.employee_reply, t.employee_reply_at, q.created_at, q.updated_at
  from public.questions q
  join private.question_threads t on t.question_id = q.id
  where public.is_everstage_user()
    and (select auth.uid()) is not null
    and q.id = p_question_id
    and p_thread_hash ~ '^[0-9a-f]{64}$'
    and t.token_hash = p_thread_hash;
$$;

create or replace function public.respond_to_unask_clarification(
  p_question_id bigint,
  p_thread_hash text,
  p_reply text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private, public
as $$
declare
  v_reply text := btrim(coalesce(p_reply, ''));
  v_changed bigint;
begin
  if not public.is_everstage_user() or (select auth.uid()) is null then
    raise exception 'Verified Everstage access is required';
  end if;
  if p_thread_hash is null or p_thread_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid thread capability';
  end if;
  if char_length(v_reply) not between 1 and 4000 then
    raise exception 'Reply must be between 1 and 4000 characters';
  end if;

  update private.question_threads t
  set employee_reply = v_reply,
      employee_reply_at = now(),
      updated_at = now()
  from public.questions q
  where t.question_id = p_question_id
    and q.id = t.question_id
    and q.status = 'Needs clarification'
    and t.token_hash = p_thread_hash;
  get diagnostics v_changed = row_count;
  if v_changed = 0 then
    raise exception 'Clarification request not found';
  end if;

  update public.questions
  set status = 'Under review', updated_at = now()
  where id = p_question_id;
end;
$$;

create or replace function public.get_unask_hr_thread(p_question_id bigint)
returns table (private_reply text, employee_reply text, employee_reply_at timestamptz)
language sql
stable
security definer
set search_path = pg_catalog, private, public
as $$
  select t.private_reply, t.employee_reply, t.employee_reply_at
  from private.question_threads t
  where public.is_everstage_user()
    and (select auth.uid()) is not null
    and private.current_staff_role() = 'hr'
    and t.question_id = p_question_id;
$$;

create or replace function public.moderate_unask_thought(
  p_thought_id bigint,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private, public
as $$
declare
  v_question_id bigint;
  v_body text;
begin
  if not public.is_everstage_user()
    or (select auth.uid()) is null
    or private.current_staff_role() <> 'hr' then
    raise exception 'HR access is required';
  end if;
  if p_action not in ('hide', 'publish', 'delete') then
    raise exception 'Invalid moderation action';
  end if;

  select qt.question_id, qt.body into v_question_id, v_body
  from public.question_thoughts qt
  where qt.id = p_thought_id
  for update;
  if not found then
    raise exception 'Thought not found';
  end if;

  if p_action = 'delete' then
    delete from public.question_thoughts where id = p_thought_id;
  else
    update public.question_thoughts
    set status = (case when p_action = 'hide' then 'hidden' else 'published' end)::public.question_thought_status,
        updated_at = now()
    where id = p_thought_id;
  end if;

  insert into private.question_audit_events (question_id, actor_user_id, action, details)
  values (
    v_question_id,
    (select auth.uid()),
    'thought_' || p_action,
    jsonb_build_object('thought_id', p_thought_id, 'body_sha256', encode(extensions.digest(v_body, 'sha256'), 'hex'))
  );
end;
$$;

create or replace function public.submit_unask_report(
  p_target_type text,
  p_target_id bigint,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private, public, extensions
as $$
declare
  v_reason text := btrim(coalesce(p_reason, ''));
  v_question_id bigint;
  v_reporter_hash text;
begin
  if not public.is_everstage_user() or (select auth.uid()) is null then
    raise exception 'Verified Everstage access is required';
  end if;
  if p_target_type not in ('question', 'thought') then
    raise exception 'Invalid report target';
  end if;
  if char_length(v_reason) not between 3 and 1000 then
    raise exception 'Report reason must be between 3 and 1000 characters';
  end if;

  if p_target_type = 'question' then
    select q.id into v_question_id
    from public.questions q
    where q.id = p_target_id and q.status in ('Assigned', 'Answered');
  else
    select qt.question_id into v_question_id
    from public.question_thoughts qt
    join public.questions q on q.id = qt.question_id
    where qt.id = p_target_id and qt.status = 'published' and q.status in ('Assigned', 'Answered');
  end if;
  if v_question_id is null then
    raise exception 'Published content not found';
  end if;

  v_reporter_hash := encode(
    extensions.digest((select auth.uid())::text || ':' || p_target_type || ':' || p_target_id::text, 'sha256'),
    'hex'
  );

  insert into private.content_reports (
    target_type, target_id, question_id, reporter_hash, reason
  ) values (
    p_target_type, p_target_id, v_question_id, v_reporter_hash, v_reason
  )
  on conflict (target_type, target_id, reporter_hash)
  do update set reason = excluded.reason, status = 'open', updated_at = now();
end;
$$;

create or replace function public.get_unask_report_counts()
returns table (question_id bigint, open_reports bigint)
language sql
stable
security definer
set search_path = pg_catalog, private, public
as $$
  select cr.question_id, count(*)::bigint
  from private.content_reports cr
  where public.is_everstage_user()
    and (select auth.uid()) is not null
    and private.current_staff_role() = 'hr'
    and cr.status = 'open'
  group by cr.question_id;
$$;

revoke all on function public.get_unask_recovery_vault(text) from public, anon;
revoke all on function public.save_unask_recovery_vault(text, text, text, text, integer) from public, anon;
revoke all on function public.get_unask_question_thread(bigint, text) from public, anon;
revoke all on function public.respond_to_unask_clarification(bigint, text, text) from public, anon;
revoke all on function public.get_unask_hr_thread(bigint) from public, anon;
revoke all on function public.moderate_unask_thought(bigint, text) from public, anon;
revoke all on function public.submit_unask_report(text, bigint, text) from public, anon;
revoke all on function public.get_unask_report_counts() from public, anon;

grant execute on function public.get_unask_recovery_vault(text) to authenticated;
grant execute on function public.save_unask_recovery_vault(text, text, text, text, integer) to authenticated;
grant execute on function public.get_unask_question_thread(bigint, text) to authenticated;
grant execute on function public.respond_to_unask_clarification(bigint, text, text) to authenticated;
grant execute on function public.get_unask_hr_thread(bigint) to authenticated;
grant execute on function public.moderate_unask_thought(bigint, text) to authenticated;
grant execute on function public.submit_unask_report(text, bigint, text) to authenticated;
grant execute on function public.get_unask_report_counts() to authenticated;

comment on table private.recovery_vaults
  is 'Stores only client-encrypted anonymous thread recovery bundles, addressed by a recovery-phrase hash.';
comment on function public.respond_to_unask_clarification(bigint, text, text)
  is 'Lets an anonymous thread holder reply to HR without recording their authenticated user ID.';
comment on function public.moderate_unask_thought(bigint, text)
  is 'Lets HR hide, restore, or permanently delete a thought with a staff audit event.';
comment on function public.submit_unask_report(text, bigint, text)
  is 'Creates one pseudonymous abuse report per employee and content target.';
